export const ROUTES = {
  landing: "/",
  consultant_dashboard: "/consultant-dashboard",
  blog: "/blog",
  about_us: "/about-us",
  auth: "/auth",
  login: "/auth/login",
  signup: "/auth/signup",
  verification: "/auth/verification",
  client_dashboard: "/client-dashboard",
  client_home: "/client-home",
  consultant_home: "/consultant-home",
  chat: "/chat",
  consultant_chat: "/consultant-chat",
  request_medication: "/request-medication",
  consultant_activities: "/consultant-activities",
};
